global: 
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'wsl'
    static_configs:
      - targets:
        - '172.19.0.1:9100'
  - job_name: 'windows'
    static_configs:
      - targets:
        - 'host.docker.internal:5000'